version: '3.1'

services:

  adopt-new-1:
    build: .
    entrypoint: java -jar ~/docker-boxing-new.jar && tail -f /dev/null
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 1s
      retries: 40
      start_period: 0s
      timeout: 10s

  adopt-new-2:
    build: .
    entrypoint: java -jar ~/docker-boxing-new.jar && tail -f /dev/null
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 1s
      retries: 40
      start_period: 0s
      timeout: 10s
